<a href="https://colab.research.google.com/github/shannonshih/Tibame_GAD245-Practice-HW_0109/blob/main/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

* 參考 Python DataScience Handbook Chapter 2
* NumPy 是一個用於數值計算的 Python 套件，提供了多種功能，特別適用於處理大規模的數據集合和矩陣運算。在科學計算、機器學習、數據分析等領域有著廣泛的應用。
* https://numpy.org/
* https://numpy.org/doc/stable/user/index.html

In [ ]:
# 安裝套件
# ! pip install numpy

In [1]:
# 宣告並載入套件
import numpy as np
import random

# Numpy的速度

In [2]:
# 產生大量的測試用資料
x = random.sample(range(0, 1000000), 1000000)

### 使用Python原生程式進行大量計算所需時間

In [3]:
import statistics

In [4]:
%%time
statistics.mean(x)

CPU times: user 478 ms, sys: 0 ns, total: 478 ms
Wall time: 479 ms


499999.5

### 使用Numpy進行同樣計算所需的時間

In [5]:
nx = np.array(x)

In [6]:
%%time
nx.mean()

CPU times: user 2.4 ms, sys: 0 ns, total: 2.4 ms
Wall time: 2.41 ms


499999.5

# 建立Numpy Array

In [7]:
# 整數的陣列
nx1 = np.array([1,2,3,4,5])
nx1

array([1, 2, 3, 4, 5])

In [8]:
# 浮點數的陣列
x = [1.0, 2, 3.2, 4, 5]
nx2 = np.array(x)
nx2

array([1. , 2. , 3.2, 4. , 5. ])

In [16]:
# 練習題
# 請建立一個 2~12之間全部偶數的陣列
# start : 從某數開始，預設為0
# stop : 到某數停止(不包含)
# step : 間格多少
# dtype : bool(布林值), int(整數), float(浮點數), complex(複數)
x = [2, 4, 6, 8, 10, 12]
print(np.array(x))
x = np.arange(2, 13, 2, int)
print(x)

[ 2  4  6  8 10 12]
[ 2  4  6  8 10 12]


Python List 中每個元素都可以是不同的資料型態

In [17]:
type(x[0])

numpy.int64

In [18]:
type(x[1])

numpy.int64

但是Numpy底層是以原生的C語言array來儲存資料，所以必須同樣的資料型態

In [ ]:
nx1.dtype

In [ ]:
nx2.dtype

### 單一變數時 C語言與Python的儲存差異
![%E5%9C%96%E7%89%87.png](attachment:%E5%9C%96%E7%89%87.png)
圖片來源 Python Data Science Handbook




### 陣列資料下 Numpy 與 Python的儲存差異
![%E5%9C%96%E7%89%87.png](attachment:%E5%9C%96%E7%89%87.png)
圖片來源 Python Data Science Handbook




In [19]:
# 指定資料型態
x = [1,2,3,4,5]
nx = np.array(x,dtype='float64')
nx

array([1., 2., 3., 4., 5.])

In [20]:
# 練習題
# 請修改下面的程式碼，讓nx陣列裡的數值都是整數
x = [1.2, 3.5, 4.2, 2.1]
nx = np.array(x)
nx = np.array(x,dtype='int64')
print(nx)

[1 3 4 2]


### Numpy的可用數值型態
資料來源 Python Data Science Handbook

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)|
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)|
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)|
| ``int8``      | Byte (-128 to 127)|
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)|
| ``uint8``     | Unsigned integer (0 to 255)|
| ``uint16``    | Unsigned integer (0 to 65535)|
| ``uint32``    | Unsigned integer (0 to 4294967295)|
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)|
| ``float_``    | Shorthand for ``float64``.|
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
| ``complex_``  | Shorthand for ``complex128``.|
| ``complex64`` | Complex number, represented by two 32-bit floats|
| ``complex128``| Complex number, represented by two 64-bit floats|

In [21]:
# 二維陣列
x = [[1,2,3], [4,5,6], [7,8,9]]
nx = np.array(x)
nx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 產生固定數值的陣列
np.zeros(5)

In [ ]:
np.ones(5)

In [ ]:
np.full(5, 3.1415)

In [ ]:
# 產生固定數值得多維陣列
np.full((3,4), 2.17)

In [ ]:
# 練習題
# 請產生一個 5 x 3全部值為 1 的陣列

In [ ]:
#產生數列
np.arange(0, 30, 3)

In [ ]:
#產生均分的數列
np.linspace(0, 1, 5)

In [25]:
# 練習題
# 請產生 [0, 10, 20, 30, ...., 90, 100] 的陣列
result_array = np.arange(0, 101, 10)
print(result_array)

[  0  10  20  30  40  50  60  70  80  90 100]


In [ ]:
#產生隨機數列
np.random.random((3, 3))

In [30]:
# 練習題
# 請產生一個 4x5的陣列 裡面的值都隨機的介於 0.2 ~ 0.5 之間
result_array1 = np.random.random((4, 5)) * 0.2, 0.5
print("result_array1 = ", result_array1)
result_array2 = np.random.uniform(0.2, 0.5, size = (4, 5))
print("result_array2 = ", result_array2)

result_array1 =  (array([[0.02415311, 0.16941419, 0.0467864 , 0.15278604, 0.1110142 ],
       [0.07460316, 0.0974089 , 0.14044826, 0.08828406, 0.04204142],
       [0.12683506, 0.178953  , 0.16565011, 0.17492159, 0.0391102 ],
       [0.15012124, 0.16490746, 0.15896141, 0.05059562, 0.02692674]]), 0.5)
result_array2 =  [[0.41560112 0.42415245 0.38204475 0.40730691 0.43566127]
 [0.24178682 0.20133413 0.4629888  0.24998143 0.30799894]
 [0.33855465 0.41189728 0.24870872 0.25554322 0.34514167]
 [0.26966034 0.27521355 0.49664615 0.41098885 0.43457263]]


In [38]:
#產生符合高斯分布的隨機數列
# 第一個參數 mean
# 第二個參數 sd
np.random.normal(0, 1, (3, 3))

array([[-0.19588487, -0.74260636,  1.50531832],
       [-0.80401177, -0.35046204,  1.96846138],
       [ 0.67579793, -1.52464248,  0.00554716]])

![%E5%9C%96%E7%89%87-4.png](attachment:%E5%9C%96%E7%89%87-4.png)

In [ ]:
# 練習題
# 假設男性平均身高為 170公分，標準差為5公分
# 請產生 7 個常態分佈下隨機的男性身高數值
result_array1 = np.random.normal(170, 5, 7)
print("result_array1 = ", result_array1)
result_array2 = np.random.randint(170, 5, 7)
print("result_array2 = ", result_array2)

In [ ]:
# 產生指定範圍內的隨機整數數列
np.random.randint(0, 10, (3, 3))

In [34]:
# 練習題
# 請模擬一個6面骰子擲出 5 次的結果
result_array1 = np.random.randint(1, 7, 5)
print("result_array1 = ", result_array1)

result_array1 =  [6 4 3 3 4]


In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpy數列屬性

In [ ]:
nx = np.random.randint(10, size=(3, 4))
nx

In [ ]:
nx.ndim #數列維度

In [ ]:
nx.shape

In [ ]:
nx.size

In [ ]:
nx.itemsize

In [ ]:
nx.nbytes

## Numpy取值

In [41]:
x = np.random.randint(0, 10, (3, 4))
x

array([[5, 1, 2, 3],
       [9, 7, 8, 5],
       [7, 0, 0, 0]])

In [ ]:
x[0]

In [ ]:
x[0,2]

In [ ]:
x[-1]

In [ ]:
x[1,1] = -4.5
x

In [42]:
x[1:3,2:4]

array([[8, 5],
       [0, 0]])

In [ ]:
x[1:3,:]

In [44]:
# 練習題
# xt 為全班這次的考試成績，請取出前三名最高的成績
# 排序可以使用 np.sort(xt)
xt = np.random.randint(0, 100, 10)
print(xt)
print(np.sort(xt))
print(xt[-3:])

[25 36 27 89 86 66 78  9 89 47]
[ 9 25 27 36 47 66 78 86 89 89]
[ 9 89 47]


### 修改數列切片內容會影響到原本的數列

In [ ]:
y = x[1:3,2:4]
y

In [ ]:
# 修改切片出來的值
y[0,0] = 3
y

In [ ]:
#原本的數列跟著改變
x

### 如果不想要引響原本的資料，可以用複製

In [ ]:
y2 = y.copy()
y2[0,0] = 7
y2

In [ ]:
y

### 改變數列形狀

In [ ]:
x = np.random.randint(0, 10, (3, 4))
x

In [ ]:
y = x.reshape(12)
y

In [ ]:
# 練習題
# 請分別將x改變成 4x3 跟 2x6 的矩陣
x = np.random.randint(0, 10, (3, 4))
print(x)

In [ ]:
# 就算修改的數列的形狀，還是一樣會影響原先的資料
y[0] = -1
y

In [ ]:
x

In [ ]:
x.reshape((2,3,2))

In [ ]:
#修改後的數列大小必須一樣
x.reshape((4,4))

## 數列結合

In [45]:
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])
x3 = np.array([x1,x2])
x3

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])
x3 = np.concatenate([x1,x2])
x3

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 修改concatenate後的數列
x3[0] = -1
x3

In [ ]:
# 不會引響到原先的數列
x1

In [ ]:
# 練習題
# 問題
# 使用下面方法結合成的x3，如果修改值會影響到x1嗎？
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])
x3 = np.array([x1,x2])

In [ ]:
# 多維數列的結合
x1 = np.array([[1, 2, 3], [4, 5, 6]])
x3 = np.concatenate([x1,x1])
x3

In [ ]:
# 改變結合的方向(軸、維度)
x3 = np.concatenate([x1,x1], axis=1)
x3

In [47]:
# 練習題
# 請將x1跟x2結合成一個 2 x 2 x 7的矩陣
x1 = np.random.randint(0,10,(2,2,3))
print('x1 = ', x1)
x2 = np.random.randint(0,10,(2,2,4))
print('x1 = ', x2)


x1 =  [[[5 7 9]
  [2 8 7]]

 [[3 2 7]
  [0 2 6]]]
x1 =  [[[7 0 0 8]
  [8 8 1 5]]

 [[6 7 8 6]
  [4 3 8 1]]]


In [ ]:
# 陣列形狀不同時無法用concatenate來結合
x1 = np.array([[1, 2, 3], [4, 5, 6]])
x2 = np.array([7, 8, 9])
print('x1 shape = ', x1.shape)
print('x2 shape = ', x2.shape)
x3 = np.concatenate([x1,x2])
x3

In [ ]:
# 練習題
# 請問要如何把 x1 x2 結合成一個 3x3的矩陣？
# 提示 可以使用 reshape()
x1 = np.array([[1, 2, 3], [4, 5, 6]])
x2 = np.array([7, 8, 9])
print('x1 shape = ', x1.shape)
print('x2 shape = ', x2.shape)


In [ ]:
x3 = np.vstack([x1,x2])
x3

In [ ]:
x1 = np.array([[1, 2, 3], [4, 5, 6]])
x2 = np.array([[7], [8]])
print('x1 shape = ', x1.shape)
print('x2 shape = ', x2.shape)
x3 = np.hstack([x1,x2])
x3

## 數列分割

In [49]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3 = np.split(x, [3, 7])
print(x1, x2, x3)

[1 2 3] [4 5 6 7] [8 9]


In [50]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
upper, lower = np.vsplit(grid, [2])
print('upper = \n',upper)
print('lower = \n',lower)

upper = 
 [[0 1 2 3]
 [4 5 6 7]]
lower = 
 [[ 8  9 10 11]
 [12 13 14 15]]


In [52]:
left, right = np.hsplit(grid, [2])
print('left = \n', left)
print('right = \n', right)

left = 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right = 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Universal Functions

### 速度差異
即使使用Numpy來處理數據，根據程式寫法速度還是會有很大的差異

In [53]:
x = np.random.random(10000)

In [54]:
%%time
for i in range(100):
    y = np.empty(len(x))
    for n in range(len(x)):
        y[n] = 1/x[n]

CPU times: user 399 ms, sys: 0 ns, total: 399 ms
Wall time: 399 ms


In [55]:
%%time
for i in range(100):
    y = 1 / x


CPU times: user 2.42 ms, sys: 0 ns, total: 2.42 ms
Wall time: 2.47 ms


### 使用Numpy內建的函數來進行計算

In [56]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [57]:
# 四則運算
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [58]:
np.add(x, 2)

array([2, 3, 4, 5])

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

In [63]:
# 練習題
# 請計算出 x 數列的平均值跟標準差
# 提示 np.mean()
x = np.random.normal(0,1,100)
print("x的平均值 = ", np.mean(x))
print("x的標準差 = ", np.std(x))

x的平均值 =  0.12995639352089527
x的標準差 =  0.9163583364475424


### 可以直接使用Python的函數

In [64]:
x = np.random.normal(0,1,10000)
x

array([ 0.10870331, -1.17180924,  0.73642877, ...,  1.28649579,
       -0.16120434,  1.19349488])

In [65]:
# python原生函數
%timeit abs(x)
abs(x)

3.81 µs ± 52.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


array([0.10870331, 1.17180924, 0.73642877, ..., 1.28649579, 0.16120434,
       1.19349488])

In [66]:
# numpy函數
%timeit np.abs(x)
np.abs(x)

5.03 µs ± 856 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


array([0.10870331, 1.17180924, 0.73642877, ..., 1.28649579, 0.16120434,
       1.19349488])

更多的UFunc API參考文件<BR>
https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

# 索引(index)操作

In [67]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
# 這種取值的方法不好
[x[1],x[3],x[5]]

[1, 3, 5]

In [69]:
# 正確的索引取值方法
x[[1,3,5]]

array([1, 3, 5])

In [70]:
# 透過變數傳遞索引
index = [1,3,5]
x[index]

array([1, 3, 5])

In [ ]:
# 練習題
# 找出 x 之中的偶數
x = np.random.randint(0,10,20)
print(x)


In [71]:
# 練習題
# 找出班上同學有達到及格分數的全部成績
score = np.random.randint(0,100,50)
print(score)
score[score >= 60]

[43 61 17  9 51 55 66 83 48  5 46 92 87 14 38 44 27 89 84 97 48 71 82 68
 45 31 32 64 20 24 28 87 96 12 74 83 13 28 30  2 26 70  5 37 11 25 95 85
  8 70]


array([61, 66, 83, 92, 87, 89, 84, 97, 71, 82, 68, 64, 87, 96, 74, 83, 70,
       95, 85, 70])

### 利用索引來改變值

In [ ]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
x

In [ ]:
x[i] -= 10
x

In [ ]:
# 練習題
# 找出班上同學有達到及格分數的全部成績
# 請根據score的分數，在ispass上填上 '及格' 或是 '不及格'
score = np.random.randint(0,100,50)
print(score)
ispass = np.full(50, '不知道')
ispass

### 如果索引值重複可能會有不可預期的問題

In [ ]:
x = np.zeros(10)
x

In [ ]:
x[[0,0]] = [1,2]
x

In [ ]:
x = np.zeros(10)
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

In [ ]:
x = np.zeros(10)
np.add.at(x, i, 1)
x

In [ ]:
# 使用at()範例
np.random.seed(42)
x = np.random.randn(100)

# compute a histogram by hand
bins = np.linspace(-5, 5, 20)
counts = np.zeros_like(bins)

# find the appropriate bin for each x
i = np.searchsorted(bins, x)

# add 1 to each of these bins
np.add.at(counts, i, 1)

import matplotlib.pyplot as plt
plt.step(bins, counts)

## 排序 Sort

In [ ]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)
x

In [ ]:
x.sort()
x

In [ ]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
i

In [ ]:
x[i]

### 多維的排序

In [76]:
rand = np.random.RandomState(42)
x = rand.randint(0, 10, (4, 6))
print(x)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [77]:
np.sort(x)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [78]:
#指定排序的軸
np.sort(x, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

## 練習題

In [75]:
# 練習題
# 請算出每位學生的五科總分
score = np.random.randint(0,100,(10,5))
print(np.sort(score))


[[23 76 87 91 95]
 [18 45 46 60 95]
 [ 3 47 71 75 96]
 [ 1  6 60 69 87]
 [ 1 21 44 80 81]
 [11 12 19 40 66]
 [14 15 30 42 71]
 [ 3 17 57 59 79]
 [ 8 38 39 79 83]
 [ 5 42 44 68 99]]


In [ ]:
# 練習題
# 請算出每位學生的五科平均
score = np.random.randint(0,100,(10,5))
score

# 自主學習內容
請參考 Python DataScience Handbook ch2.4之後的章節